services:
  worklune-redis: 
      image: redis:7-alpine
      container_name: worklune-redis
      command: >
        redis-server
        --requirepass abc$1289
        --appendonly yes
      ports:
        - "6379:6379"
      volumes:
      - redis_data:/data
      restart: unless-stopped

volumes:
  redis_data:  