services:
  worklune-redis: 
      image: redis:7-alpine
      container_name: worklune-redis
      command: >
        redis-server
        --requirepass abc$1289
        --appendonly yes
      ports:
        - "6379:6379"
      volumes:
      - redis_data:/data
      restart: unless-stopped
  
  worklune-pgDb:
    image: postgres:14.20-alpine
    container_name: worklune-pgDb
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abc1234
      POSTGRES_DB: worlune_db
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:  
      - 8080:8080
  
  worklune-mq:
    image: rabbitmq:latest
    container_name: worklune-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: abcd1234
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]." 

volumes:
  redis_data:  
  pgsql_data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local